"""
Project Euler 45

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""
def getPen(index):
    """
    Gets the pentagonal number at the given index
    """
    return int(index * (3 * index - 1) / 2)

def main():
    hexIndex = 144
    penIndex = 144

    while True:
        hexagonal = int(hexIndex * (2 * hexIndex - 1))

        latestPen = getPen(penIndex)
        
        while latestPen < hexagonal:
            penIndex += 1
            latestPen = getPen(penIndex)

        if (hexagonal == latestPen):
            print(hexagonal)
            break

        hexIndex += 1

main()
